### ISSUE TITLE
求助 已按照要求配置session-token   Mode为openai和google 都会报error accessToken

### ISSUE THREAD

**Issue by Karmau-Git** [nek0us/nonebot-plugin-gpt#4]
![image](https://github.com/nek0us/nonebot-plugin-gpt/assets/118444525/e37a2da7-9e1c-46db-84c9-d22ec062065b)

**Comment by Karmau-Git** [comment]
![context sjk105392@gmail com faild!](https://github.com/nek0us/nonebot-plugin-gpt/assets/118444525/c8644cdc-ff32-49f3-8312-66b2d0a8f913)

输出出来的图片

**Comment by nek0us** [comment]
明天我看看，今天还在忙

**Comment by Karmau-Git** [comment]
> 明天我看看，今天还在忙

好的 谢谢

**Comment by nek0us** [comment]
已更新，再试试

**Comment by Enceladus6** [comment]
我之前是这个问题，更新后现在已经可以正常使用了
