### ISSUE TITLE
只有提示GPT登录中 之后无法触发插件  登录失败是有日志以及图片的

### ISSUE THREAD

**Issue by Karmau-Git** [nek0us/nonebot-plugin-gpt#5]
![image](https://github.com/nek0us/nonebot-plugin-gpt/assets/118444525/5bf09589-9cba-48fc-b058-97fc4db5f771)
![image](https://github.com/nek0us/nonebot-plugin-gpt/assets/118444525/97b7c277-80c6-446a-a593-7367ec92a117)

**Comment by nek0us** [comment]
可以把nb配置文件中的log level改为DEBUG就能看见更多日志了，有时候可能因为各种原因还没有登陆完，需要看DEBUG日志和登录错误截图。假如是正常正在登陆中，可以通过`工作状态`指令查看登录情况

**Comment by Karmau-Git** [comment]
![image](https://github.com/nek0us/nonebot-plugin-gpt/assets/118444525/8a6d393b-03a5-4625-b3ad-1502a7ba182e)
![image](https://github.com/nek0us/nonebot-plugin-gpt/assets/118444525/edd3f6f3-e2a2-42d0-ad8b-6d304d3bbb88)

**Comment by nek0us** [comment]
看日志是登录成功了，看事件响应器是没响应到，你是开启了白名单模式吗

**Comment by Karmau-Git** [comment]
好啦 可以用了 有点蠢了  耽误您时间啦
